### ISSUE TITLE
Do I need to install teaser?

### ISSUE THREAD

**Issue by SubMishMar** [qqqGpe/DCRML#1]
I am getting this error.
![Screenshot from 2022-10-31 22-07-56](https://user-images.githubusercontent.com/28704031/199150199-17484215-66e9-4a0e-963c-e46ae43573f7.png)

**Comment by qqqGpe** [comment]
No, you don't have to install teaser, just delete this line and try again.

**Comment by SubMishMar** [comment]
Oh ok. I installed it and it compiles. Let me remove this line. Thanks! In addition to this I also needed to add `#include"iostream"` to `utility.h` , and I think you need to modify the complete path to eigen includes with something generic in your CMakeLists.txt. Perhaps using `${EIGEN3_INCLUDE_DIR}` is a better idea.

Thanks for the paper and the code. I like your work!

**Comment by SubMishMar** [comment]
Also I had to add `/usr/lib/x86_64-linux-gnu/libfmt.a` to `target_link_libraries()` for DCRML - but this is probably something that you have no control over, I am not sure.

**Comment by qqqGpe** [comment]
> Oh ok. I installed it and it compiles. Let me remove this line. Thanks! In addition to this I also needed to add `#include"iostream"` to `utility.h` , and I think you need to modify the complete path to eigen includes with something generic in your CMakeLists.txt. Perhaps using `${EIGEN3_INCLUDE_DIR}` is a better idea.
> 
> Thanks for the paper and the code. I like your work!

Thanks for the suggestion.

**Comment by qqqGpe** [comment]
> Also I had to add `/usr/lib/x86_64-linux-gnu/libfmt.a` to `target_link_libraries()` for DCRML - but this is probably something that you have no control over, I am not sure.

I didn't meet the same problem as you like, maybe this problem is caused by the old version of 'ceres'.
